name: task_manager
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1


dependencies:

  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_slidable: ^3.1.2
  ffi: ^2.1.3
  path_provider: ^2.1.5
  firebase_core: ^3.10.1
  cloud_firestore: ^5.6.2
  firebase_auth: ^5.4.2
  email_validator: ^3.0.0
  fluttertoast: ^8.2.11

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

